openapi: 3.2.0
info:
  contact:
    name: ''
  description: ''
  title: Spinnaker Credentials Controller API
servers:
- description: Generated server url
  url: http://localhost
tags:
- name: credentials-controller
paths:
  /credentials:
    get:
      operationId: getAccounts
      parameters:
      - in: query
        name: expand
        required: false
        schema:
          type: boolean
      responses:
        '200':
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Account'
                type: array
          description: OK
      summary: Retrieve a list of accounts
      tags:
      - credentials-controller
    post:
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDefinition'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountDefinition'
          description: OK
      summary: Creates a new account definition
      tags:
      - credentials-controller
    put:
      operationId: updateAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDefinition'
        required: true
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountDefinition'
          description: OK
      summary: Updates an existing account definition
      tags:
      - credentials-controller
  /credentials/type/{accountType}:
    get:
      operationId: getAccountsByType
      parameters:
      - description: Value of the "@type" key for accounts to search for.
        example: kubernetes
        in: path
        name: accountType
        required: true
        schema:
          type: string
      - description: Maximum number of entries to return in results. Used for pagination.
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
      - description: Account name to start account definition listing from. Used for pagination.
        in: query
        name: startingAccountName
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/AccountDefinition'
                type: array
          description: OK
      summary: Looks up account definitions by type
      tags:
      - credentials-controller
  /credentials/{accountName}:
    delete:
      operationId: deleteAccount
      parameters:
      - description: Name of account definition to delete.
        in: path
        name: accountName
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Deletes an account definition by name
      tags:
      - credentials-controller
  /credentials/{account}:
    get:
      operationId: getAccount
      parameters:
      - in: path
        name: account
        required: true
        schema:
          type: string
      - in: header
        name: X-RateLimit-App
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccountDetails'
          description: OK
      summary: Retrieve an account's details
      tags:
      - credentials-controller
components:
  schemas:
    AccountDefinition:
      description: Account definition body including a discriminator field named "type" with the account type.
      properties:
        name:
          type: string
        type:
          type: string
      type: object
    AccountDetails:
      properties:
        accountId:
          type: string
        accountType:
          type: string
        challengeDestructiveActions:
          type: boolean
        cloudProvider:
          type: string
        environment:
          type: string
        name:
          type: string
        permissions:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        primaryAccount:
          type: boolean
        requiredGroupMembership:
          items:
            type: string
          type: array
        type:
          type: string
      type: object
    Account:
      properties:
        accountId:
          type: string
        name:
          type: string
        permissions:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        requiredGroupMembership:
          items:
            type: string
          type: array
        type:
          type: string
      type: object
externalDocs:
  description: Spinnaker Documentation
  url: https://spinnaker.io
