openapi: 3.2.0
info:
  contact:
    name: ''
  description: ''
  title: Spinnaker Job Controller API
servers:
- description: Generated server url
  url: http://localhost
tags:
- name: job-controller
paths:
  /applications/{applicationName}/jobs/{account}/{region}/{name}:
    get:
      operationId: getJob
      parameters:
      - in: path
        name: applicationName
        required: true
        schema:
          type: string
      - in: path
        name: account
        required: true
        schema:
          type: string
      - in: path
        name: region
        required: true
        schema:
          type: string
      - in: path
        name: name
        required: true
        schema:
          type: string
      - in: query
        name: expand
        required: false
        schema:
          default: 'false'
          type: string
      - in: header
        name: X-RateLimit-App
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                additionalProperties: {}
                type: object
          description: OK
      summary: Get job
      tags:
      - job-controller
  /jobs/preconfigured:
    get:
      operationId: preconfiguredWebhooks_1
      responses:
        '200':
          content:
            '*/*':
              schema:
                items: {}
                type: array
          description: OK
      summary: Retrieve a list of preconfigured jobs in Orca
      tags:
      - job-controller
externalDocs:
  description: Spinnaker Documentation
  url: https://spinnaker.io
