openapi: 3.2.0
info:
  contact:
    name: ''
  description: ''
  title: Spinnaker Nexus Controller API
servers:
- description: Generated server url
  url: http://localhost
tags:
- name: nexus-controller
paths:
  /nexus/names:
    get:
      operationId: names
      responses:
        '200':
          content:
            '*/*':
              schema:
                items:
                  type: string
                type: array
          description: OK
      summary: Retrieve the list of nexus names available to triggers
      tags:
      - nexus-controller
externalDocs:
  description: Spinnaker Documentation
  url: https://spinnaker.io
