openapi: 3.2.0
info:
  contact:
    name: ''
  description: ''
  title: Spinnaker Ecs Secret Controller API
servers:
- description: Generated server url
  url: http://localhost
tags:
- name: ecs-secret-controller
paths:
  /ecs/secrets:
    get:
      operationId: all_8
      responses:
        '200':
          content:
            '*/*':
              schema:
                items: {}
                type: array
          description: OK
      summary: Retrieve a list of Secrets Manager secrets that can be used for the account and…
      tags:
      - ecs-secret-controller
externalDocs:
  description: Spinnaker Documentation
  url: https://spinnaker.io
